# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

springdoc.swagger-ui.default-models-expand-depth=1
springdoc.swagger-ui.default-model-expand-depth=1
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true

# Logging
logging.level.org.springdoc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Puerto del servidor
server.port=8081

# ==========================================================
# CONFIGURACIÓN DE BASE DE DATOS (MariaDB)
# ==========================================================

spring.datasource.url=jdbc:mariadb://localhost:3306/sistema_coworking
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Mostrar SQL y manejar esquema
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
